name: .NET 9 Blazor Server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 9 SDK (Preview)
      uses: actions/upload-artifact@v3.1.3
      with:
        dotnet-version: '9.0.100-preview'

    - name: Restore Dependencies
      run: dotnet restore ./UI/UI.csproj

    - name: Build Project
      run: dotnet build ./UI/UI.csproj --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish ./UI/UI.csproj --configuration Release --output ./publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: blazor-app
        path: ./publish
